spring:
  application:
    name: recruiting-microservices

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8097}



